---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - name: "Add name server into resolve.conf"
      shell: echo "nameserver {{ item }}" >> /etc/resolv.conf 
      with_items:
        - 8.8.8.8
        - 8.8.4.4
    - name: "Enable repos"
      yum:
        enanble_repo: ['base', 'clean', 'metadata']
    - name: "Install yum-utils and docker prerequisite"
      yum:
        name: ['yum-utils', 'device-mapper-persistent-data', 'lvm2']
        state: present
    - name: "Add Docker-CE repo"
      get_url:  
        url: https://download.docker.com/linux/centos/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644
    - name: "Install docker-ce and containerd.io"
      yum:
        name: ['docker-ce', 'docker-ce-cli', 'containerd.io']
        state: present
    - name: "Add vagrant user into docker group"
      user:
        name: vagrant
        groups: docker
        append: yes
    - name: "Start and enable docker service"
      service:
        name: docker      
        state: started
        enabled: yes

- hosts: all
  become_user: vagrant
  gather_facts: no
  tasks:
    - name: "Pull SPA docker image"
      docker_image:
        name: jaykay321/solution:v1
        source: pull
    - name: "Run container"
      docker_container:
        name: spa
        image: jaykay321/solution:v1
        ports:
          - "80:80"
        state: started
